patch:
  abc_segmentor/extra_tags:
    - reverse_lookup
  reverse_lookup/dictionary: jyut6ping3
  reverse_lookup/prism: jyut6ping3
  reverse_lookup/preedit_format: []
  reverse_lookup/tips: "〔粵拼〕"
  translator/dictionary: cangjie5.cj3ext
  translator/enable_encoder: false
  translator/enable_sentence: false
  translator/enable_user_dict: false
  translator/preedit_format:
    - 'xform/^([a-z]*)$/\U$1\E/'
    - "xlit|ABCDEFGHIJKLMNOPQRSTUVWXYZ|日月金木水火土竹戈十大中一弓人心手口尸廿山女田難卜符|"
