patch:
  abc_segmentor/extra_tags:
    - reverse_lookup
  reverse_lookup/dictionary: jyut6ping3.pure
  reverse_lookup/prism: jyut6ping3.pure
  reverse_lookup/preedit_format: 
    - "xform/([aeioumngptk])vv/$1⁴/"
    - "xform/([aeioumngptk])xx/$1⁵/"
    - "xform/([aeioumngptk])qq/$1⁶/"
    - "xform/([aeioumngptk])v/$1¹/"
    - "xform/([aeioumngptk])x/$1²/"
    - "xform/([aeioumngptk])q/$1³/"
  reverse_lookup/tips: "〔粵拼〕"
  translator/dictionary: cangjie5.cj3ext
  translator/enable_encoder: false
  translator/enable_sentence: false
  translator/enable_user_dict: false
  translator/preedit_format:
    - 'xform/^([a-z]*)$/\U$1\E/'
    - "xlit|ABCDEFGHIJKLMNOPQRSTUVWXYZ|日月金木水火土竹戈十大中一弓人心手口尸廿山女田難卜符|"
