patch:
  ascii_composer/good_old_caps_lock: noop
  ascii_composer/switch_key:
    Caps_Lock: noop
    Shift_L: noop
    Shift_R: noop
    Control_L: clear
    Control_R: noop
  key_binder/bindings:
    - when: paging
      accept: bracketleft
      send: Page_Up
    - when: has_menu
      accept: bracketright
      send: Page_Down
  menu/page_size: 9
  schema_list:
    - schema: cangjie5
    - schema: jyutping
