patch:
  abc_segmentor/extra_tags:
    - reverse_lookup
  reverse_lookup/dictionary: cangjie5.cj3ext
  reverse_lookup/preedit_format:
    - "xlit|abcdefghijklmnopqrstuvwxyz|日月金木水火土竹戈十大中一弓人心手口尸廿山女田難卜符|"
  reverse_lookup/tips: "〔倉頡〕"
  speller/algebra:
    - "derive/([123456])//"
    - "xform/1/v/"
    - "xform/2/x/"
    - "xform/3/q/"
    - "xform/4/vv/"
    - "xform/5/xx/"
    - "xform/6/qq/"
