patch:
  abc_segmentor/extra_tags: []
  translator/dictionary: jyut6ping3.clean
  speller/algebra:
    - "derive/([123456])//"
    - "xform/1/v/"
    - "xform/2/x/"
    - "xform/3/q/"
    - "xform/4/vv/"
    - "xform/5/xx/"
    - "xform/6/qq/"
    - "derive/eo/oe/"
    - "derive/oe(ng|k)$/eo$1/"
