---
name: kana
version: "0"
sort: original
use_preset_vocabulary: false
...

々	xx
ー	xx
ん	nn
ゃ	xya
ゅ	xyu
ょ	xyo
っ	xtsu
ン	nn
ャ	xya
ュ	xyu
ョ	xyo
ッ	xtsu
あ	a
ああ	aa
あん	an
ああん	aan
あっ	azzz
ああっ	aazzz
い	i
いい	ii
いん	in
いいん	iin
いっ	izzz
いいっ	iizzz
う	u
うう	uu
うん	un
ううん	uun
うっ	uzzz
ううっ	uuzzz
え	e
ええ	ee
えい	ei
えん	en
ええん	een
えいん	ein
えっ	ezzz
ええっ	eezzz
えいっ	eizzz
お	o
おお	oo
おう	ou
おん	on
おおん	oon
おうん	oun
おっ	ozzz
おおっ	oozzz
おうっ	ouzzz
か	ka
っか	kka
かあ	kaa
かん	kan
かあん	kaan
かっ	kazzz
かあっ	kaazzz
き	ki
っき	kki
きい	kii
きゃ	kya
きゃあ	kyaa
きゅ	kyu
きゅう	kyuu
きょ	kyo
きょお	kyoo
きょう	kyou
きん	kin
きいん	kiin
きゃん	kyan
きゃあん	kyaan
きゅん	kyun
きゅうん	kyuun
きょん	kyon
きょおん	kyoon
きょうん	kyoun
きっ	kizzz
きいっ	kiizzz
きゃっ	kyazzz
きゃあっ	kyaazzz
きゅっ	kyuzzz
きゅうっ	kyuuzzz
きょっ	kyozzz
きょおっ	kyoozzz
きょうっ	kyouzzz
く	ku
っく	kku
くう	kuu
くん	kun
くうん	kuun
くっ	kuzzz
くうっ	kuuzzz
け	ke
っけ	kke
けえ	kee
けい	kei
けん	ken
けえん	keen
けいん	kein
けっ	kezzz
けえっ	keezzz
けいっ	keizzz
こ	ko
っこ	kko
こお	koo
こう	kou
こん	kon
こおん	koon
こうん	koun
こっ	kozzz
こおっ	koozzz
こうっ	kouzzz
が	ga
っが	gga
があ	gaa
がん	gan
があん	gaan
がっ	gazzz
があっ	gaazzz
ぎ	gi
っぎ	ggi
ぎい	gii
ぎゃ	gya
ぎゃあ	gyaa
ぎゅ	gyu
ぎゅう	gyuu
ぎょ	gyo
ぎょお	gyoo
ぎょう	gyou
ぎん	gin
ぎいん	giin
ぎゃん	gyan
ぎゃあん	gyaan
ぎゅん	gyun
ぎゅうん	gyuun
ぎょん	gyon
ぎょおん	gyoon
ぎょうん	gyoun
ぎっ	gizzz
ぎいっ	giizzz
ぎゃっ	gyazzz
ぎゃあっ	gyaazzz
ぎゅっ	gyuzzz
ぎゅうっ	gyuuzzz
ぎょっ	gyozzz
ぎょおっ	gyoozzz
ぎょうっ	gyouzzz
ぐ	gu
っぐ	ggu
ぐう	guu
ぐん	gun
ぐうん	guun
ぐっ	guzzz
ぐうっ	guuzzz
げ	ge
っげ	gge
げえ	gee
げい	gei
げん	gen
げえん	geen
げいん	gein
げっ	gezzz
げえっ	geezzz
げいっ	geizzz
ご	go
っご	ggo
ごお	goo
ごう	gou
ごん	gon
ごおん	goon
ごうん	goun
ごっ	gozzz
ごおっ	goozzz
ごうっ	gouzzz
さ	sa
っさ	ssa
さあ	saa
さん	san
さあん	saan
さっ	sazzz
さあっ	saazzz
し	shi
っし	sshi
しい	shii
しゃ	sha
しゃあ	shaa
しゅ	shu
しゅう	shuu
しょ	sho
しょお	shoo
しょう	shou
しん	shin
しいん	shiin
しゃん	shan
しゃあん	shaan
しゅん	shun
しゅうん	shuun
しょん	shon
しょおん	shoon
しょうん	shoun
しっ	shizzz
しいっ	shiizzz
しゃっ	shazzz
しゃあっ	shaazzz
しゅっ	shuzzz
しゅうっ	shuuzzz
しょっ	shozzz
しょおっ	shoozzz
しょうっ	shouzzz
す	su
っす	ssu
すう	suu
すん	sun
すうん	suun
すっ	suzzz
すうっ	suuzzz
せ	se
っせ	sse
せえ	see
せい	sei
せん	sen
せえん	seen
せいん	sein
せっ	sezzz
せえっ	seezzz
せいっ	seizzz
そ	so
っそ	sso
そお	soo
そう	sou
そん	son
そおん	soon
そうん	soun
そっ	sozzz
そおっ	soozzz
そうっ	souzzz
ざ	za
っざ	zza
ざあ	zaa
ざん	zan
ざあん	zaan
ざっ	zazzz
ざあっ	zaazzz
じ	ji
っじ	jji
じい	jii
じゃ	ja
じゃあ	jaa
じゅ	ju
じゅう	juu
じょ	jo
じょお	joo
じょう	jou
じん	jin
じいん	jiin
じゃん	jan
じゃあん	jaan
じゅん	jun
じゅうん	juun
じょん	jon
じょおん	joon
じょうん	joun
じっ	jizzz
じいっ	jiizzz
じゃっ	jazzz
じゃあっ	jaazzz
じゅっ	juzzz
じゅうっ	juuzzz
じょっ	jozzz
じょおっ	joozzz
じょうっ	jouzzz
ず	zu
っず	zzu
ずう	zuu
ずん	zun
ずうん	zuun
ずっ	zuzzz
ずうっ	zuuzzz
ぜ	ze
っぜ	zze
ぜえ	zee
ぜい	zei
ぜん	zen
ぜえん	zeen
ぜいん	zein
ぜっ	zezzz
ぜえっ	zeezzz
ぜいっ	zeizzz
ぞ	zo
っぞ	zzo
ぞお	zoo
ぞう	zou
ぞん	zon
ぞおん	zoon
ぞうん	zoun
ぞっ	zozzz
ぞおっ	zoozzz
ぞうっ	zouzzz
た	ta
った	tta
たあ	taa
たん	tan
たあん	taan
たっ	tazzz
たあっ	taazzz
ち	chi
っち	cchi
ちい	chii
ちゃ	cha
ちゃあ	chaa
ちゅ	chu
ちゅう	chuu
ちょ	cho
ちょお	choo
ちょう	chou
ちん	chin
ちいん	chiin
ちゃん	chan
ちゃあん	chaan
ちゅん	chun
ちゅうん	chuun
ちょん	chon
ちょおん	choon
ちょうん	choun
ちっ	chizzz
ちいっ	chiizzz
ちゃっ	chazzz
ちゃあっ	chaazzz
ちゅっ	chuzzz
ちゅうっ	chuuzzz
ちょっ	chozzz
ちょおっ	choozzz
ちょうっ	chouzzz
つ	tsu
っつ	ttsu
つう	tsuu
つん	tsun
つうん	tsuun
つっ	tsuzzz
つうっ	tsuuzzz
て	te
って	tte
てえ	tee
てい	tei
てん	ten
てえん	teen
ていん	tein
てっ	tezzz
てえっ	teezzz
ていっ	teizzz
と	to
っと	tto
とお	too
とう	tou
とん	ton
とおん	toon
とうん	toun
とっ	tozzz
とおっ	toozzz
とうっ	touzzz
だ	da
っだ	dda
だあ	daa
だん	dan
だあん	daan
だっ	dazzz
だあっ	daazzz
ぢ	ji
っじ	jji
ぢい	jii
ぢゃ	ja
ぢゃあ	jaa
ぢゅ	ju
ぢゅう	juu
ぢょ	jo
ぢょお	joo
ぢょう	jou
ぢん	jin
ぢいん	jiin
ぢゃん	jan
ぢゃあん	jaan
ぢゅん	jun
ぢゅうん	juun
ぢょん	jon
ぢょおん	joon
ぢょうん	joun
ぢっ	jizzz
ぢいっ	jiizzz
ぢゃっ	jazzz
ぢゃあっ	jaazzz
ぢゅっ	juzzz
ぢゅうっ	juuzzz
ぢょっ	jozzz
ぢょおっ	joozzz
ぢょうっ	jouzzz
づ	zu
っず	zzu
づう	zuu
づん	zun
づうん	zuun
づっ	zuzzz
づうっ	zuuzzz
で	de
っで	dde
でえ	dee
でい	dei
でん	den
でえん	deen
でいん	dein
でっ	dezzz
でえっ	deezzz
でいっ	deizzz
ど	do
っど	ddo
どお	doo
どう	dou
どん	don
どおん	doon
どうん	doun
どっ	dozzz
どおっ	doozzz
どうっ	douzzz
な	na
なあ	naa
なん	nan
なあん	naan
なっ	nazzz
なあっ	naazzz
に	ni
にい	nii
にゃ	nya
にゃあ	nyaa
にゅ	nyu
にゅう	nyuu
にょ	nyo
にょお	nyoo
にょう	nyou
にん	nin
にいん	niin
にゃん	nyan
にゃあん	nyaan
にゅん	nyun
にゅうん	nyuun
にょん	nyon
にょおん	nyoon
にょうん	nyoun
にっ	nizzz
にいっ	niizzz
にゃっ	nyazzz
にゃあっ	nyaazzz
にゅっ	nyuzzz
にゅうっ	nyuuzzz
にょっ	nyozzz
にょおっ	nyoozzz
にょうっ	nyouzzz
ぬ	nu
ぬう	nuu
ぬん	nun
ぬうん	nuun
ぬっ	nuzzz
ぬうっ	nuuzzz
ね	ne
ねえ	nee
ねい	nei
ねん	nen
ねえん	neen
ねいん	nein
ねっ	nezzz
ねえっ	neezzz
ねいっ	neizzz
の	no
のお	noo
のう	nou
のん	non
のおん	noon
のうん	noun
のっ	nozzz
のおっ	noozzz
のうっ	nouzzz
は	ha
はあ	haa
はん	han
はあん	haan
はっ	hazzz
はあっ	haazzz
ひ	hi
ひい	hii
ひゃ	hya
ひゃあ	hyaa
ひゅ	hyu
ひゅう	hyuu
ひょ	hyo
ひょお	hyoo
ひょう	hyou
ひん	hin
ひいん	hiin
ひゃん	hyan
ひゃあん	hyaan
ひゅん	hyun
ひゅうん	hyuun
ひょん	hyon
ひょおん	hyoon
ひょうん	hyoun
ひっ	hizzz
ひいっ	hiizzz
ひゃっ	hyazzz
ひゃあっ	hyaazzz
ひゅっ	hyuzzz
ひゅうっ	hyuuzzz
ひょっ	hyozzz
ひょおっ	hyoozzz
ひょうっ	hyouzzz
ふ	fu
ふう	fuu
ふん	fun
ふうん	fuun
ふっ	fuzzz
ふうっ	fuuzzz
へ	he
へえ	hee
へい	hei
へん	hen
へえん	heen
へいん	hein
へっ	hezzz
へえっ	heezzz
へいっ	heizzz
ほ	ho
ほお	hoo
ほう	hou
ほん	hon
ほおん	hoon
ほうん	houn
ほっ	hozzz
ほおっ	hoozzz
ほうっ	houzzz
ば	ba
っば	bba
ばあ	baa
ばん	ban
ばあん	baan
ばっ	bazzz
ばあっ	baazzz
び	bi
っび	bbi
びい	bii
びゃ	bya
びゃあ	byaa
びゅ	byu
びゅう	byuu
びょ	byo
びょお	byoo
びょう	byou
びん	bin
びいん	biin
びゃん	byan
びゃあん	byaan
びゅん	byun
びゅうん	byuun
びょん	byon
びょおん	byoon
びょうん	byoun
びっ	bizzz
びいっ	biizzz
びゃっ	byazzz
びゃあっ	byaazzz
びゅっ	byuzzz
びゅうっ	byuuzzz
びょっ	byozzz
びょおっ	byoozzz
びょうっ	byouzzz
ぶ	bu
っぶ	bbu
ぶう	buu
ぶん	bun
ぶうん	buun
ぶっ	buzzz
ぶうっ	buuzzz
べ	be
っべ	bbe
べえ	bee
べい	bei
べん	ben
べえん	been
べいん	bein
べっ	bezzz
べえっ	beezzz
べいっ	beizzz
ぼ	bo
っぼ	bbo
ぼお	boo
ぼう	bou
ぼん	bon
ぼおん	boon
ぼうん	boun
ぼっ	bozzz
ぼおっ	boozzz
ぼうっ	bouzzz
ぱ	pa
っぱ	ppa
ぱあ	paa
ぱん	pan
ぱあん	paan
ぱっ	pazzz
ぱあっ	paazzz
ぴ	pi
っぴ	ppi
ぴい	pii
ぴゃ	pya
ぴゃあ	pyaa
ぴゅ	pyu
ぴゅう	pyuu
ぴょ	pyo
ぴょお	pyoo
ぴょう	pyou
ぴん	pin
ぴいん	piin
ぴゃん	pyan
ぴゃあん	pyaan
ぴゅん	pyun
ぴゅうん	pyuun
ぴょん	pyon
ぴょおん	pyoon
ぴょうん	pyoun
ぴっ	pizzz
ぴいっ	piizzz
ぴゃっ	pyazzz
ぴゃあっ	pyaazzz
ぴゅっ	pyuzzz
ぴゅうっ	pyuuzzz
ぴょっ	pyozzz
ぴょおっ	pyoozzz
ぴょうっ	pyouzzz
ぷ	pu
っぷ	ppu
ぷう	puu
ぷん	pun
ぷうん	puun
ぷっ	puzzz
ぷうっ	puuzzz
ぺ	pe
っぺ	ppe
ぺえ	pee
ぺい	pei
ぺん	pen
ぺえん	peen
ぺいん	pein
ぺっ	pezzz
ぺえっ	peezzz
ぺいっ	peizzz
ぽ	po
っぽ	ppo
ぽお	poo
ぽう	pou
ぽん	pon
ぽおん	poon
ぽうん	poun
ぽっ	pozzz
ぽおっ	poozzz
ぽうっ	pouzzz
ま	ma
まあ	maa
まん	man
まあん	maan
まっ	mazzz
まあっ	maazzz
み	mi
みい	mii
みゃ	mya
みゃあ	myaa
みゅ	myu
みゅう	myuu
みょ	myo
みょお	myoo
みょう	myou
みん	min
みいん	miin
みゃん	myan
みゃあん	myaan
みゅん	myun
みゅうん	myuun
みょん	myon
みょおん	myoon
みょうん	myoun
みっ	mizzz
みいっ	miizzz
みゃっ	myazzz
みゃあっ	myaazzz
みゅっ	myuzzz
みゅうっ	myuuzzz
みょっ	myozzz
みょおっ	myoozzz
みょうっ	myouzzz
む	mu
むう	muu
むん	mun
むうん	muun
むっ	muzzz
むうっ	muuzzz
め	me
めえ	mee
めい	mei
めん	men
めえん	meen
めいん	mein
めっ	mezzz
めえっ	meezzz
めいっ	meizzz
も	mo
もお	moo
もう	mou
もん	mon
もおん	moon
もうん	moun
もっ	mozzz
もおっ	moozzz
もうっ	mouzzz
や	ya
やあ	yaa
やん	yan
やあん	yaan
やっ	yazzz
やあっ	yaazzz
ゆ	yu
ゆう	yuu
ゆん	yun
ゆうん	yuun
ゆっ	yuzzz
ゆうっ	yuuzzz
よ	yo
よお	yoo
よう	you
よん	yon
よおん	yoon
ようん	youn
よっ	yozzz
よおっ	yoozzz
ようっ	youzzz
ら	ra
らあ	raa
らん	ran
らあん	raan
らっ	razzz
らあっ	raazzz
り	ri
りい	rii
りゃ	rya
りゃあ	ryaa
りゅ	ryu
りゅう	ryuu
りょ	ryo
りょお	ryoo
りょう	ryou
りん	rin
りいん	riin
りゃん	ryan
りゃあん	ryaan
りゅん	ryun
りゅうん	ryuun
りょん	ryon
りょおん	ryoon
りょうん	ryoun
りっ	rizzz
りいっ	riizzz
りゃっ	ryazzz
りゃあっ	ryaazzz
りゅっ	ryuzzz
りゅうっ	ryuuzzz
りょっ	ryozzz
りょおっ	ryoozzz
りょうっ	ryouzzz
る	ru
るう	ruu
るん	run
るうん	ruun
るっ	ruzzz
るうっ	ruuzzz
れ	re
れえ	ree
れい	rei
れん	ren
れえん	reen
れいん	rein
れっ	rezzz
れえっ	reezzz
れいっ	reizzz
ろ	ro
ろお	roo
ろう	rou
ろん	ron
ろおん	roon
ろうん	roun
ろっ	rozzz
ろおっ	roozzz
ろうっ	rouzzz
わ	wa
わあ	waa
わん	wan
わあん	waan
わっ	wazzz
わあっ	waazzz
を	wo
をお	woo
をう	wou
をん	won
をおん	woon
をうん	woun
をっ	wozzz
をおっ	woozzz
をうっ	wouzzz
ア	a
ッア	aa
アー	aa
アン	an
アーン	aan
アッ	azzz
アーッ	aazzz
イ	i
ッイ	ii
イー	ii
イン	in
イーン	iin
イッ	izzz
イーッ	iizzz
ウ	u
ッウ	uu
ウー	uu
ウン	un
ウーン	uun
ウッ	uzzz
ウーッ	uuzzz
エ	e
ッエ	ee
エー	ee
エー	ei
エン	en
エーン	een
エーン	ein
エッ	ezzz
エーッ	eezzz
エーッ	eizzz
オ	o
ッオ	oo
オー	oo
オー	ou
オン	on
オーン	oon
オーン	oun
オッ	ozzz
オーッ	oozzz
オーッ	ouzzz
カ	ka
ッカ	kka
カー	kaa
カン	kan
カーン	kaan
カッ	kazzz
カーッ	kaazzz
キ	ki
ッキ	kki
キー	kii
キャ	kya
キャー	kyaa
キュ	kyu
キュー	kyuu
キョ	kyo
キョー	kyoo
キョー	kyou
キン	kin
キーン	kiin
キャン	kyan
キャーン	kyaan
キュン	kyun
キューン	kyuun
キョン	kyon
キョーン	kyoon
キョーン	kyoun
キッ	kizzz
キーッ	kiizzz
キャッ	kyazzz
キャーッ	kyaazzz
キュッ	kyuzzz
キューッ	kyuuzzz
キョッ	kyozzz
キョーッ	kyoozzz
キョーッ	kyouzzz
ク	ku
ック	kku
クー	kuu
クン	kun
クーン	kuun
クッ	kuzzz
クーッ	kuuzzz
ケ	ke
ッケ	kke
ケー	kee
ケー	kei
ケン	ken
ケーン	keen
ケーン	kein
ケッ	kezzz
ケーッ	keezzz
ケーッ	keizzz
コ	ko
ッコ	kko
コー	koo
コー	kou
コン	kon
コーン	koon
コーン	koun
コッ	kozzz
コーッ	koozzz
コーッ	kouzzz
ガ	ga
ッガ	gga
ガー	gaa
ガン	gan
ガーン	gaan
ガッ	gazzz
ガーッ	gaazzz
ギ	gi
ッギ	ggi
ギー	gii
ギャ	gya
ギャー	gyaa
ギュ	gyu
ギュー	gyuu
ギョ	gyo
ギョー	gyoo
ギョー	gyou
ギン	gin
ギーン	giin
ギャン	gyan
ギャーン	gyaan
ギュン	gyun
ギューン	gyuun
ギョン	gyon
ギョーン	gyoon
ギョーン	gyoun
ギッ	gizzz
ギーッ	giizzz
ギャッ	gyazzz
ギャーッ	gyaazzz
ギュッ	gyuzzz
ギューッ	gyuuzzz
ギョッ	gyozzz
ギョーッ	gyoozzz
ギョーッ	gyouzzz
グ	gu
ッグ	ggu
グー	guu
グン	gun
グーン	guun
グッ	guzzz
グーッ	guuzzz
ゲ	ge
ッゲ	gge
ゲー	gee
ゲー	gei
ゲン	gen
ゲーン	geen
ゲーン	gein
ゲッ	gezzz
ゲーッ	geezzz
ゲーッ	geizzz
ゴ	go
ッゴ	ggo
ゴー	goo
ゴー	gou
ゴン	gon
ゴーン	goon
ゴーン	goun
ゴッ	gozzz
ゴーッ	goozzz
ゴーッ	gouzzz
サ	sa
ッサ	ssa
サー	saa
サン	san
サーン	saan
サッ	sazzz
サーッ	saazzz
シ	shi
ッシ	sshi
シー	shii
シャ	sha
シャー	shaa
シュ	shu
シュー	shuu
ショ	sho
ショー	shoo
ショー	shou
シン	shin
シーン	shiin
シャン	shan
シャーン	shaan
シュン	shun
シューン	shuun
ション	shon
ショーン	shoon
ショーン	shoun
シッ	shizzz
シーッ	shiizzz
シャッ	shazzz
シャーッ	shaazzz
シュッ	shuzzz
シューッ	shuuzzz
ショッ	shozzz
ショーッ	shoozzz
ショーッ	shouzzz
ス	su
ッス	ssu
スー	suu
スン	sun
スーン	suun
スッ	suzzz
スーッ	suuzzz
セ	se
ッセ	sse
セー	see
セー	sei
セン	sen
セーン	seen
セーン	sein
セッ	sezzz
セーッ	seezzz
セーッ	seizzz
ソ	so
ッソ	sso
ソー	soo
ソー	sou
ソン	son
ソーン	soon
ソーン	soun
ソッ	sozzz
ソーッ	soozzz
ソーッ	souzzz
ザ	za
ッザ	zza
ザー	zaa
ザン	zan
ザーン	zaan
ザッ	zazzz
ザーッ	zaazzz
ジ	ji
ッジ	jji
ジー	jii
ジャ	ja
ジャー	jaa
ジュ	ju
ジュー	juu
ジョ	jo
ジョー	joo
ジョー	jou
ジン	jin
ジーン	jiin
ジャン	jan
ジャーン	jaan
ジュン	jun
ジューン	juun
ジョン	jon
ジョーン	joon
ジョーン	joun
ジッ	jizzz
ジーッ	jiizzz
ジャッ	jazzz
ジャーッ	jaazzz
ジュッ	juzzz
ジューッ	juuzzz
ジョッ	jozzz
ジョーッ	joozzz
ジョーッ	jouzzz
ズ	zu
ッズ	zzu
ズー	zuu
ズン	zun
ズーン	zuun
ズッ	zuzzz
ズーッ	zuuzzz
ゼ	ze
ッゼ	zze
ゼー	zee
ゼー	zei
ゼン	zen
ゼーン	zeen
ゼーン	zein
ゼッ	zezzz
ゼーッ	zeezzz
ゼーッ	zeizzz
ゾ	zo
ッゾ	zzo
ゾー	zoo
ゾー	zou
ゾン	zon
ゾーン	zoon
ゾーン	zoun
ゾッ	zozzz
ゾーッ	zoozzz
ゾーッ	zouzzz
タ	ta
ッタ	tta
ター	taa
タン	tan
ターン	taan
タッ	tazzz
ターッ	taazzz
チ	chi
ッチ	cchi
チー	chii
チャ	cha
チャー	chaa
チュ	chu
チュー	chuu
チョ	cho
チョー	choo
チョー	chou
チン	chin
チーン	chiin
チャン	chan
チャーン	chaan
チュン	chun
チューン	chuun
チョン	chon
チョーン	choon
チョーン	choun
チッ	chizzz
チーッ	chiizzz
チャッ	chazzz
チャーッ	chaazzz
チュッ	chuzzz
チューッ	chuuzzz
チョッ	chozzz
チョーッ	choozzz
チョーッ	chouzzz
ツ	tsu
ッツ	ttsu
ツー	tsuu
ツン	tsun
ツーン	tsuun
ツッ	tsuzzz
ツーッ	tsuuzzz
テ	te
ッテ	tte
テー	tee
テー	tei
テン	ten
テーン	teen
テーン	tein
テッ	tezzz
テーッ	teezzz
テーッ	teizzz
ト	to
ット	tto
トー	too
トー	tou
トン	ton
トーン	toon
トーン	toun
トッ	tozzz
トーッ	toozzz
トーッ	touzzz
ダ	da
ッダ	dda
ダー	daa
ダン	dan
ダーン	daan
ダッ	dazzz
ダーッ	daazzz
ヂ	ji
ッジ	jji
ヂー	jii
ヂャ	ja
ヂャー	jaa
ヂュ	ju
ヂュー	juu
ヂョ	jo
ヂョー	joo
ヂョー	jou
ヂン	jin
ヂーン	jiin
ヂャン	jan
ヂャーン	jaan
ヂュン	jun
ヂューン	juun
ヂョン	jon
ヂョーン	joon
ヂョーン	joun
ヂッ	jizzz
ヂーッ	jiizzz
ヂャッ	jazzz
ヂャーッ	jaazzz
ヂュッ	juzzz
ヂューッ	juuzzz
ヂョッ	jozzz
ヂョーッ	joozzz
ヂョーッ	jouzzz
ヅ	zu
ッズ	zzu
ヅー	zuu
ヅン	zun
ヅーン	zuun
ヅッ	zuzzz
ヅーッ	zuuzzz
デ	de
ッデ	dde
デー	dee
デー	dei
デン	den
デーン	deen
デーン	dein
デッ	dezzz
デーッ	deezzz
デーッ	deizzz
ド	do
ッド	ddo
ドー	doo
ドー	dou
ドン	don
ドーン	doon
ドーン	doun
ドッ	dozzz
ドーッ	doozzz
ドーッ	douzzz
ナ	na
ッナ	nna
ナー	naa
ナン	nan
ナーン	naan
ナッ	nazzz
ナーッ	naazzz
ニ	ni
ッニ	nni
ニー	nii
ニャ	nya
ニャー	nyaa
ニュ	nyu
ニュー	nyuu
ニョ	nyo
ニョー	nyoo
ニョー	nyou
ニン	nin
ニーン	niin
ニャン	nyan
ニャーン	nyaan
ニュン	nyun
ニューン	nyuun
ニョン	nyon
ニョーン	nyoon
ニョーン	nyoun
ニッ	nizzz
ニーッ	niizzz
ニャッ	nyazzz
ニャーッ	nyaazzz
ニュッ	nyuzzz
ニューッ	nyuuzzz
ニョッ	nyozzz
ニョーッ	nyoozzz
ニョーッ	nyouzzz
ヌ	nu
ッヌ	nnu
ヌー	nuu
ヌン	nun
ヌーン	nuun
ヌッ	nuzzz
ヌーッ	nuuzzz
ネ	ne
ッネ	nne
ネー	nee
ネー	nei
ネン	nen
ネーン	neen
ネーン	nein
ネッ	nezzz
ネーッ	neezzz
ネーッ	neizzz
ノ	no
ッノ	nno
ノー	noo
ノー	nou
ノン	non
ノーン	noon
ノーン	noun
ノッ	nozzz
ノーッ	noozzz
ノーッ	nouzzz
ハ	ha
ッハ	hha
ハー	haa
ハン	han
ハーン	haan
ハッ	hazzz
ハーッ	haazzz
ヒ	hi
ッヒ	hhi
ヒー	hii
ヒャ	hya
ヒャー	hyaa
ヒュ	hyu
ヒュー	hyuu
ヒョ	hyo
ヒョー	hyoo
ヒョー	hyou
ヒン	hin
ヒーン	hiin
ヒャン	hyan
ヒャーン	hyaan
ヒュン	hyun
ヒューン	hyuun
ヒョン	hyon
ヒョーン	hyoon
ヒョーン	hyoun
ヒッ	hizzz
ヒーッ	hiizzz
ヒャッ	hyazzz
ヒャーッ	hyaazzz
ヒュッ	hyuzzz
ヒューッ	hyuuzzz
ヒョッ	hyozzz
ヒョーッ	hyoozzz
ヒョーッ	hyouzzz
フ	fu
ッフ	ffu
フー	fuu
フン	fun
フーン	fuun
フッ	fuzzz
フーッ	fuuzzz
へ	he
ッへ	hhe
へー	hee
へー	hei
へン	hen
へーン	heen
へーン	hein
へッ	hezzz
へーッ	heezzz
へーッ	heizzz
ホ	ho
ッホ	hho
ホー	hoo
ホー	hou
ホン	hon
ホーン	hoon
ホーン	houn
ホッ	hozzz
ホーッ	hoozzz
ホーッ	houzzz
バ	ba
ッバ	bba
バー	baa
バン	ban
バーン	baan
バッ	bazzz
バーッ	baazzz
ビ	bi
ッビ	bbi
ビー	bii
ビャ	bya
ビャー	byaa
ビュ	byu
ビュー	byuu
ビョ	byo
ビョー	byoo
ビョー	byou
ビン	bin
ビーン	biin
ビャン	byan
ビャーン	byaan
ビュン	byun
ビューン	byuun
ビョン	byon
ビョーン	byoon
ビョーン	byoun
ビッ	bizzz
ビーッ	biizzz
ビャッ	byazzz
ビャーッ	byaazzz
ビュッ	byuzzz
ビューッ	byuuzzz
ビョッ	byozzz
ビョーッ	byoozzz
ビョーッ	byouzzz
ブ	bu
ッブ	bbu
ブー	buu
ブン	bun
ブーン	buun
ブッ	buzzz
ブーッ	buuzzz
ベ	be
ッベ	bbe
ベー	bee
ベー	bei
ベン	ben
ベーン	been
ベーン	bein
ベッ	bezzz
ベーッ	beezzz
ベーッ	beizzz
ボ	bo
ッボ	bbo
ボー	boo
ボー	bou
ボン	bon
ボーン	boon
ボーン	boun
ボッ	bozzz
ボーッ	boozzz
ボーッ	bouzzz
パ	pa
ッパ	ppa
パー	paa
パン	pan
パーン	paan
パッ	pazzz
パーッ	paazzz
ピ	pi
ッピ	ppi
ピー	pii
ピャ	pya
ピャー	pyaa
ピュ	pyu
ピュー	pyuu
ピョ	pyo
ピョー	pyoo
ピョー	pyou
ピン	pin
ピーン	piin
ピャン	pyan
ピャーン	pyaan
ピュン	pyun
ピューン	pyuun
ピョン	pyon
ピョーン	pyoon
ピョーン	pyoun
ピッ	pizzz
ピーッ	piizzz
ピャッ	pyazzz
ピャーッ	pyaazzz
ピュッ	pyuzzz
ピューッ	pyuuzzz
ピョッ	pyozzz
ピョーッ	pyoozzz
ピョーッ	pyouzzz
プ	pu
ップ	ppu
プー	puu
プン	pun
プーン	puun
プッ	puzzz
プーッ	puuzzz
ぺ	pe
ッぺ	ppe
ぺー	pee
ぺー	pei
ぺン	pen
ぺーン	peen
ぺーン	pein
ぺッ	pezzz
ぺーッ	peezzz
ぺーッ	peizzz
ポ	po
ッポ	ppo
ポー	poo
ポー	pou
ポン	pon
ポーン	poon
ポーン	poun
ポッ	pozzz
ポーッ	poozzz
ポーッ	pouzzz
マ	ma
ッマ	mma
マー	maa
マン	man
マーン	maan
マッ	mazzz
マーッ	maazzz
ミ	mi
ッミ	mmi
ミー	mii
ミャ	mya
ミャー	myaa
ミュ	myu
ミュー	myuu
ミョ	myo
ミョー	myoo
ミョー	myou
ミン	min
ミーン	miin
ミャン	myan
ミャーン	myaan
ミュン	myun
ミューン	myuun
ミョン	myon
ミョーン	myoon
ミョーン	myoun
ミッ	mizzz
ミーッ	miizzz
ミャッ	myazzz
ミャーッ	myaazzz
ミュッ	myuzzz
ミューッ	myuuzzz
ミョッ	myozzz
ミョーッ	myoozzz
ミョーッ	myouzzz
ム	mu
ッム	mmu
ムー	muu
ムン	mun
ムーン	muun
ムッ	muzzz
ムーッ	muuzzz
メ	me
ッメ	mme
メー	mee
メー	mei
メン	men
メーン	meen
メーン	mein
メッ	mezzz
メーッ	meezzz
メーッ	meizzz
モ	mo
ッモ	mmo
モー	moo
モー	mou
モン	mon
モーン	moon
モーン	moun
モッ	mozzz
モーッ	moozzz
モーッ	mouzzz
ヤ	ya
ッヤ	yya
ヤー	yaa
ヤン	yan
ヤーン	yaan
ヤッ	yazzz
ヤーッ	yaazzz
ユ	yu
ッユ	yyu
ユー	yuu
ユン	yun
ユーン	yuun
ユッ	yuzzz
ユーッ	yuuzzz
ヨ	yo
ッヨ	yyo
ヨー	yoo
ヨー	you
ヨン	yon
ヨーン	yoon
ヨーン	youn
ヨッ	yozzz
ヨーッ	yoozzz
ヨーッ	youzzz
ラ	ra
ッラ	rra
ラー	raa
ラン	ran
ラーン	raan
ラッ	razzz
ラーッ	raazzz
リ	ri
ッリ	rri
リー	rii
リャ	rya
リャー	ryaa
リュ	ryu
リュー	ryuu
リョ	ryo
リョー	ryoo
リョー	ryou
リン	rin
リーン	riin
リャン	ryan
リャーン	ryaan
リュン	ryun
リューン	ryuun
リョン	ryon
リョーン	ryoon
リョーン	ryoun
リッ	rizzz
リーッ	riizzz
リャッ	ryazzz
リャーッ	ryaazzz
リュッ	ryuzzz
リューッ	ryuuzzz
リョッ	ryozzz
リョーッ	ryoozzz
リョーッ	ryouzzz
ル	ru
ッル	rru
ルー	ruu
ルン	run
ルーン	ruun
ルッ	ruzzz
ルーッ	ruuzzz
レ	re
ッレ	rre
レー	ree
レー	rei
レン	ren
レーン	reen
レーン	rein
レッ	rezzz
レーッ	reezzz
レーッ	reizzz
ロ	ro
ッロ	rro
ロー	roo
ロー	rou
ロン	ron
ローン	roon
ローン	roun
ロッ	rozzz
ローッ	roozzz
ローッ	rouzzz
ワ	wa
ッワ	wwa
ワー	waa
ワン	wan
ワーン	waan
ワッ	wazzz
ワーッ	waazzz
ヲ	wo
ッヲ	wwo
ヲー	woo
ヲー	wou
ヲン	won
ヲーン	woon
ヲーン	woun
ヲッ	wozzz
ヲーッ	woozzz
ヲーッ	wouzzz
