---
name: kana
version: "0"
sort: original
use_preset_vocabulary: false
...

ァ	xa
ぁ	xa
ア	a
あ	a
ィ	xi
ぃ	xi
イ	i
い	i
ゥ	xu
ぅ	xu
ウ	u
う	u
ヴ	vu
ゔ	vu
ヴァ	va
ゔぁ	va
ヴィ	vi
ゔぃ	vi
ヴェ	ve
ゔぇ	ve
ヴォ	vo
ゔぉ	vo
ヴャ	vya
ゔゃ	vya
ヴュ	vyu
ゔゅ	vyu
ヴョ	vyo
ゔょ	vyo
ェ	xe
ぇ	xe
エ	e
え	e
ォ	xo
ぉ	xo
オ	o
お	o
ヵ	xka
ゕ	xka
カ	ka
か	ka
ガ	ga
が	ga
キ	ki
き	ki
ギ	gi
ぎ	gi
キャ	kya
きゃ	kya
ギャ	gya
ぎゃ	gya
キィ	kyi
きぃ	kyi
ギィ	gyi
ぎぃ	gyi
キュ	kyu
きゅ	kyu
ギュ	gyu
ぎゅ	gyu
キェ	kye
きィ	kye
ギェ	gye
ぎィ	gye
キョ	kyo
きょ	kyo
ギョ	gyo
ぎょ	gyo
ク	ku
く	ku
グ	gu
ぐ	gu
くゎ	kwa
ぐゎ	gwa
ヶ	xke
ゖ	xke
ケ	ke
け	ke
ゲ	ge
げ	ge
コ	ko
こ	ko
ゴ	go
ご	go
サ	sa
さ	sa
ザ	za
ざ	za
シ	si
し	si
ジ	zi
じ	zi
シャ	sya
しゃ	sya
ジャ	zya
じゃ	zya
シィ	syi
しぃ	syi
ジィ	zyi
じぃ	zyi
シュ	syu
しゅ	syu
ジュ	zyu
じゅ	zyu
シェ	sye
しぇ	sye
ジェ	zye
じぇ	zye
ショ	syo
しょ	syo
ジョ	zyo
じょ	zyo
ス	su
す	su
ズ	zu
ず	zu
セ	se
せ	se
ゼ	ze
ぜ	ze
ソ	so
そ	so
ゾ	zo
ぞ	zo
タ	ta
た	ta
ダ	da
だ	da
チ	ti
ち	ti
ヂ	di
ぢ	di
チャ	tya
ちゃ	tya
ヂャ	dya
ぢゃ	dya
チィ	tyi
ちぃ	tyi
ヂィ	dyi
ぢぃ	dyi
チュ	tyu
ちゅ	tyu
ヂュ	dyu
ぢゅ	dyu
チェ	tye
ちぇ	tye
ヂェ	dye
ぢぇ	dye
チョ	tyo
ちょ	tyo
ヂョ	dyo
ぢょ	dyo
ッ	xtsu
っ	xtsu
ツ	tsu
つ	tsu
ヅ	du
づ	du
ッカ	kka
っか	kka
ッガ	gga
ッキ	kki
っき	kki
ッギ	ggi
ッキャ	kkya
っきゃ	kkya
ッギャ	ggya
ッキュ	kkyu
っきゅ	kkyu
ッギュ	ggyu
ッキョ	kkyo
っきょ	kkyo
ッギョ	ggyo
ック	kku
っく	kku
ッグ	ggu
ッケ	kke
っけ	kke
ッゲ	gge
ッコ	kko
っこ	kko
ッゴ	ggo
ッサ	ssa
っさ	ssa
ッザ	zza
ッシ	ssi
っし	ssi
ッジ	zzi
ッシャ	ssya
っしゃ	ssya
ッジャ	zzya
ッシュ	ssyu
っしゅ	ssyu
ッジュ	zzyu
ッショ	ssyo
っしょ	ssyo
ッジョ	zzyo
ッス	ssu
っす	ssu
ッズ	zzu
ッセ	sse
っせ	sse
ッゼ	zze
ッソ	sso
っそ	sso
ッゾ	zzo
ッタ	tta
った	tta
ッダ	dda
ッチ	tti
っち	tti
ッヂ	ddi
ッチャ	ttya
っちゃ	ttya
ッヂャ	ddya
ッチュ	ttyu
っちゅ	ttyu
ッヂュ	ddyu
ッチョ	ttyo
っちょ	ttyo
ッヂョ	ddyo
ッツ	ttu
っつ	ttu
ッヅ	ddu
ッテ	tte
って	tte
ッデ	dde
ット	tto
っと	tto
ッド	ddo
ッハ	hha
ッバ	bba
ッパ	ppa
っぱ	ppa
ッヒ	hhi
ッビ	bbi
ッピ	ppi
っぴ	ppi
ッヒャ	hhya
ッビャ	bbya
ッピャ	ppya
っぴゃ	ppya
ッヒュ	hhyu
ッビュ	bbyu
ッピュ	ppyu
っぴゅ	ppyu
ッヒョ	hhyo
ッビョ	bbyo
ッピョ	ppyo
っぴょ	ppyo
ッフ	hhu
ッブ	bbu
ップ	ppu
っぷ	ppu
ッヘ	hhe
ッベ	bbe
ッペ	ppe
っぺ	ppe
ッホ	hho
ッボ	bbo
ッポ	ppo
っぽ	ppo
テ	te
て	te
デ	de
で	de
ト	to
と	to
ド	do
ど	do
ツァ	tsa
つぁ	tsa
ツィ	tsi
つぃ	tsi
ツェ	tse
つぇ	tse
ツォ	tso
つぉ	tso
ヅァ	dza
づぁ	dza
ヅィ	dzi
づぃ	dzi
ヅェ	dze
づぇ	dze
ヅォ	dzo
づぉ	dzo
ナ	na
な	na
ニ	ni
に	ni
ニャ	nya
にゃ	nya
ニィ	nyi
にぃ	nyi
ニュ	nyu
にゅ	nyu
ニェ	nye
にぇ	nye
ニョ	nyo
にょ	nyo
ヌ	nu
ぬ	nu
ネ	ne
ね	ne
ノ	no
の	no
ハ	ha
は	ha
バ	ba
ば	ba
パ	pa
ぱ	pa
ヒ	hi
ひ	hi
ビ	bi
び	bi
ピ	pi
ぴ	pi
ヒャ	hya
ひゃ	hya
ビャ	bya
びゃ	bya
ピャ	pya
ぴゃ	pya
ヒ	hyi
ひ	hyi
ビ	byi
び	byi
ピ	pyi
ぴ	pyi
ヒュ	hyu
ひゅ	hyu
ビュ	byu
びゅ	byu
ピュ	pyu
ぴゅ	pyu
ヒェ	hye
ひぇ	hye
ビェ	bye
びぇ	bye
ピェ	pye
ぴぇ	pye
ヒョ	hyo
ひょ	hyo
ビョ	byo
びょ	byo
ピョ	pyo
ぴょ	pyo
フ	hu
ふ	hu
ブ	bu
ぶ	bu
プ	pu
ぷ	pu
ファ	fa
フィ	fi
フェ	fe
フォ	fo
ヘ	he
へ	he
ベ	be
べ	be
ペ	pe
ぺ	pe
ホ	ho
ほ	ho
ボ	bo
ぼ	bo
ポ	po
ぽ	po
マ	ma
ま	ma
ミ	mi
み	mi
ミャ	mya
みゃ	mya
ミィ	myi
みィ	myi
ミュ	myu
みゅ	myu
ミェ	mye
みぇ	mye
ミョ	myo
みょ	myo
ム	mu
む	mu
メ	me
め	me
モ	mo
も	mo
ャ	xya
ゃ	xya
ヤ	ya
や	ya
ュ	xyu
ゅ	xyu
ユ	yu
ゆ	yu
ョ	xyo
ょ	xyo
ヨ	yo
よ	yo
ラ	ra
ら	ra
リ	ri
り	ri
リャ	rya
りゃ	rya
リィ	ryi
りぃ	ryi
リュ	ryu
りゅ	ryu
リェ	rye
りぇ	rye
リョ	ryo
りょ	ryo
ル	ru
る	ru
レ	re
れ	re
ロ	ro
ろ	ro
ヮ	xwa
ゎ	xwa
ワ	wa
わ	wa
ヷ	va
ヰ	wi
ゐ	wi
ヸ	vi
ヱ	we
ゑ	we
ヹ	ve
ヲ	wo
を	wo
ヺ	vo
ン	n
ん	n
ー	-
